SCENARIOS = [
    {
        "id": "cold",
        "title": "1. Cold compute",
        "kind": "single",
        "summary": "First card on purpose: any other button that talks to Neon wakes compute and you lose the shot. Wake time is added to TTFT when the allow-list runs before the first token.",
        "steps": [
            "Before this card: do not click Warm up, DB ping, Run on any other card, or Refresh logs. Those all hit Neon.",
            "In the Neon console, confirm compute is Idle (short autosuspend helps).",
            "Click Run (or DB ping fresh if you want to skip the model). This is the first DB hit.",
            "Immediately Run again without waiting. That second hit is warm compute.",
        ],
        "look_for": "First connect ms is hundreds of ms to several seconds. Second run’s connect ms drops hard. Query ms stays small both times.",
    },
    {
        "id": "connect",
        "title": "2. New TLS connection",
        "kind": "single",
        "summary": "Compute is warm now. A new psycopg.connect() per allow-list check still pays TLS + auth. The SELECT is cheap.",
        "steps": [
            "Click DB ping (fresh), then DB ping (pooled). No model call.",
            "Click Run. This chat path uses a fresh TLS connection before the stream.",
            "Keep these connect vs query numbers for the next cards.",
        ],
        "look_for": "Fresh ping: connect ms ≫ query ms. Pooled ping: connect ms is 0 (socket already open). Run: TTFT includes that connect ms.",
    },
    {
        "id": "baseline",
        "title": "3. Stream first",
        "kind": "single",
        "summary": "The control. Tokens start without waiting on Neon. Allow-list and logging happen off the event loop.",
        "steps": [
            "Warm up DB so later cards are not measuring TLS or wake.",
            "Click Run. Note TTFT and client TTFT.",
            "Run a second time. Use this as the comparison number for every later card.",
        ],
        "look_for": "TTFT tracks the model only. connect ms, query ms, and pool wait ms on the critical path stay 0.",
    },
    {
        "id": "serial",
        "title": "4. Allow-list, then stream",
        "kind": "single",
        "summary": "Classic ordering bug: wait for a pooled allow-list SELECT, then open the model. Same SQL as a healthy check; wrong place on the timeline.",
        "steps": [
            "Warm up DB if you skipped it on Stream first.",
            "Click Run.",
            "Compare TTFT to Stream first. The extra should be about query ms, not connect ms.",
        ],
        "look_for": "TTFT ≈ baseline + one round trip. connect ms is 0 because the pool is warm. This is the old block_db=1 demo.",
    },
    {
        "id": "gather",
        "title": "5. Parallel, then yield",
        "kind": "single",
        "summary": "Allow-list and the model HTTP connect run at the same time, but the first token is withheld until both finish. Parallel work is not the same as overlapping TTFT.",
        "steps": [
            "Warm up DB.",
            "Click Run.",
            "Compare to Stream first and to Allow-list then stream.",
        ],
        "look_for": "TTFT is max(db, model connect), not model-only. If Neon is slow, this looks as bad as serial. If Neon is fast, it may look close to baseline — that is the point of the next card.",
    },
    {
        "id": "rtts",
        "title": "6. Four round trips",
        "kind": "single",
        "summary": "User, org, role, and flag as four sequential SELECTs on a warm connection. Chatty allow-lists add RTT even when each query is trivial.",
        "steps": [
            "Warm up DB.",
            "Click Run.",
            "Compare query ms and round trips to Allow-list then stream (one SELECT).",
        ],
        "look_for": "round trips = 4. query ms is roughly 4× serial. TTFT grows with trips, not with SQL complexity.",
    },
    {
        "id": "loop",
        "title": "7. Sync DB freezes the loop",
        "kind": "pair_sequence",
        "summary": "A single request cannot show this. Request A blocks the asyncio loop with a sync Neon call. Request B is an innocent stream whose wait for the first token includes that stall.",
        "steps": [
            "Click Run pair (one click starts both).",
            "Victim starts first: a normal Stream-first chat.",
            "Blocker then sends one meta event and runs a sync connect + pg_sleep(1) on the loop (no model call).",
            "Compare victim client TTFT to Stream first.",
        ],
        "look_for": "Blocker TTFT is tiny. Victim TTFT is ~1s+ higher even though that request never waited on the allow-list itself. Logging after a stream can still hurt the next user.",
    },
    {
        "id": "hold",
        "title": "8. Hold the pool slot",
        "kind": "pair_parallel",
        "summary": "Also needs two overlapping chats. Pool size 1: checkout for the allow-list, then keep the slot while the model streams. The other request queues before it may start the model.",
        "steps": [
            "Click Run pair. Both chats start at once.",
            "The winner streams with max_tokens capped so the demo ends.",
            "Watch pool wait ms on the loser vs Stream first.",
        ],
        "look_for": "One TTFT is near baseline. The other has large pool wait ms, on the order of the first stream’s duration. The loop is not frozen — only the slot is.",
    },
    {
        "id": "nat",
        "title": "9. IP allow list / NAT hop",
        "kind": "explain",
        "summary": "Not runnable in-app. Serverless egress IPs rotate, so an IP allow list usually forces a static NAT or proxy. Every checkout pays an extra hop; a wrong IP pays connect_timeout.",
        "steps": [
            "There is no Run on this card — it is a network path, not SQL.",
            "Compare a direct Neon connection from this VM to the same query through a NAT gateway or proxy whose IP is listed.",
            "Misconfig: list the wrong IP and watch retries until connect_timeout (10s in this app) fold into TTFT.",
        ],
        "look_for": "Success: a small constant add on connect ms for every new connection. Failure: multi-second TTFT or errors, not a slow SELECT.",
    },
]
