SCENARIOS = [
    {
        "id": "baseline",
        "title": "Stream first",
        "kind": "single",
        "summary": "Allow-list and logging run off the event loop after tokens start. This is the control.",
        "steps": [
            "Optional: click Warm up DB so the pool is already open.",
            "Click Run once. Note TTFT.",
            "Run a second time. Use this number as the comparison for every other card.",
        ],
        "look_for": "TTFT should track the model only. db_connect_ms and db_query_ms stay 0 on the critical path.",
    },
    {
        "id": "serial",
        "title": "Allow-list, then stream",
        "kind": "single",
        "summary": "The request waits for a pooled allow-list SELECT before it opens the model stream.",
        "steps": [
            "Warm up DB first so you are measuring the query, not TLS.",
            "Click Run.",
            "Compare TTFT to baseline. The delta should be about db_query_ms.",
        ],
        "look_for": "TTFT ≈ baseline + one round trip. Same order bug as the old block_db flag.",
    },
    {
        "id": "gather",
        "title": "Parallel, then yield",
        "kind": "single",
        "summary": "Allow-list and the model HTTP connect run together, but the first token is withheld until both finish.",
        "steps": [
            "Warm up DB.",
            "Click Run.",
            "Compare to baseline and to serial.",
        ],
        "look_for": "TTFT is max(db, model connect), not model-only. If Neon is slow, this looks as bad as serial.",
    },
    {
        "id": "connect",
        "title": "New TLS connection",
        "kind": "single",
        "summary": "Allow-list does psycopg.connect() every time. The query is cheap; the handshake is not.",
        "steps": [
            "Click DB ping (fresh). Note connect_ms vs query_ms.",
            "Click Run. This path uses a new TLS connection before the model.",
            "Compare db_connect_ms to serial's db_query_ms on a warm pool.",
        ],
        "look_for": "connect_ms dominates. The allow-list SQL is not the cost.",
    },
    {
        "id": "cold",
        "title": "Cold compute",
        "kind": "single",
        "summary": "Same code as a fresh connect, after Neon has suspended. Wake time lands in TTFT.",
        "steps": [
            "In the Neon console, set autosuspend short (or leave the default).",
            "Idle until compute shows Idle, or wait ~5 minutes.",
            "Do not click Warm up. Click Run (or DB ping fresh) as the first hit.",
            "Immediately Run again. That second hit is warm.",
        ],
        "look_for": "First connect_ms is hundreds of ms to several seconds. Second run collapses toward the connect card.",
    },
    {
        "id": "rtts",
        "title": "Four round trips",
        "kind": "single",
        "summary": "User, org, role, and flag checks as four sequential SELECTs on a warm connection.",
        "steps": [
            "Warm up DB.",
            "Click Run.",
            "Compare db_query_ms and round_trips to serial (one SELECT).",
        ],
        "look_for": "TTFT grows with round_trips, not with query complexity. One indexed lookup (or a cache) would flatten this.",
    },
    {
        "id": "loop",
        "title": "Sync DB freezes the loop",
        "kind": "pair_sequence",
        "summary": "Request A blocks the event loop with a sync Neon call after its first byte. Request B is an innocent stream whose TTFT includes that stall.",
        "steps": [
            "Click Run pair. The UI starts the victim stream first, then the blocker.",
            "Victim is a normal baseline chat (model call).",
            "Blocker does not call the model: it sends one meta event, then a sync Neon connect + pg_sleep(1) on the event loop.",
            "Compare victim client TTFT to a baseline run. Server TTFT on the victim should also jump if the stall overlapped the wait for the first token.",
        ],
        "look_for": "Blocker TTFT is tiny. Victim TTFT is ~1s+ extra even though it never waited on DB itself.",
    },
    {
        "id": "hold",
        "title": "Hold the pool slot",
        "kind": "pair_parallel",
        "summary": "Pool size 1. Each request checks out a slot, then streams the model while still holding it.",
        "steps": [
            "Click Run pair. Both chats start at once and share a one-slot pool.",
            "The winner streams with max_tokens capped so the demo ends.",
            "The loser waits for the slot before it may open the model.",
        ],
        "look_for": "One TTFT is normal. The other has a large pool_wait_ms, about as long as the first stream.",
    },
    {
        "id": "nat",
        "title": "IP allow list / NAT hop",
        "kind": "explain",
        "summary": "Serverless egress IPs rotate. An IP allow list usually forces a static NAT or proxy, so every checkout takes an extra hop.",
        "steps": [
            "This one is not runnable in-app (it is a network path, not an SQL bug).",
            "Compare a direct Neon connection from this VM to the same query through a NAT gateway or proxy with a listed IP.",
            "Misconfig: list the wrong IP and watch connect_timeout (10s here) fold into TTFT.",
        ],
        "look_for": "Successful path: a small constant add to connect_ms. Failed path: retries until 10s.",
    },
]
